#起動条件とかの書き方は下記がわかりやすい
#https://qiita.com/delphinus/items/00ff2c0ba972c6e41542

#ディレクトリ構造を見るやつ
[[plugins]]
repo = 'scrooloose/nerdtree'

#カラースキーム
#ターミナルの色もいじる必要がある(iterm2じゃないとテーマが用意されてなくてきついかも)
#詳しくはgithubのページに行けばわかる
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add='''
set background=dark
colorscheme hybrid_material
if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif
'''

#tomlファイルのシンタックスハイライト
[[plugins]]
repo = 'cespare/vim-toml'
#on_ft=['toml']	本当はこれ入れたいが入れるとプラグインが動かない

#deopleteのために必要その1
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

#deopleteのために必要その2
[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'
