#補完するやつ
#python3、pip3によるpyvimのインスコが必要(githubのrequirmentをよく読む)
#homebrewでpython3入れるとpip3入らなくてキレそう(https://teratail.com/questions/126801)
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add='''
let g:deoplete#enable_at_startup = 1
"call deoplete#custom#var('clangx', 'clang_binary', '/usr/bin/clang')
" バックスペースで補完のポップアップを閉じたいができない
"inoremap <silent><expr><BS> pumvisible() ? deoplete#smart_close_popup(): "\<BS>"
"inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
"inoremap <expr><BS> deoplete#close_popup()."<C-h>"
'''

#スニペット
[[plugins]]
repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets', 'context_filetype.vim']
depends = ['neosnippet-snippets']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_add='''
" タブキーで補完候補の選択. スニペット内のジャンプもタブキーでジャンプ
imap <expr><TAB>
	 \ pumvisible() ? "\<C-n>" :
	 \ neosnippet#expandable_or_jumpable() ?
	 \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
" エンターキーでスニペット挿入or補完確定orポップアップ閉じる
imap <expr><CR>
	\ (pumvisible() && neosnippet#expandable()) ? "\<Plug>(neosnippet_expand)" :
	\ pumvisible() ? deoplete#close_popup() :"\<CR>"
"ユーザースニペットのやつ呼び出すコマンド長スギ
command Snip :NeoSnippetEdit
"スニペットの場所を指定
let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
'''

#基本のスニペット入ってるやつ
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
depends=['Shougo/deoplete.nvim']
on_event = 'InsertCharPre'
hook_add = '''
'''

[[plugins]]
repo = 'lervag/vimtex'
hook_post_source = '''
    let g:vimtex_compiler_latexmk = {
          \ 'background': 0,
          \ 'build_dir': '',
          \ 'continuous': 1,
          \ 'options': [
          \    '-pdfdvi',
          \    '-verbose',
          \    '-file-line-error',
          \    '-synctex=1',
          \    '-interaction=nonstopmode',
          \],
          \}
    
"    let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    let g:vimtex_view_general_options = '@line @pdf @tex'
    " texのconcealを無効化　有効だとバチクソ見にくい
    "let g:tex_conceal=''
	call deoplete#custom#var('omni', 'input_patterns', {
	          \ 'tex': g:vimtex#re#deoplete
	          \})
'''
